name       : httpd
version    : 2.4.54
release    : 24
source     :
    - https://downloads.apache.org/httpd/httpd-2.4.54.tar.bz2 : eb397feeefccaf254f8d45de3768d9d68e8e73851c49afd5b7176d1ecf80c340
license    : Apache-2.0
component  : programming
summary    : A secure, efficient and extensible server that provides HTTP services in sync with the current HTTP standards
description: |
    A secure, efficient and extensible server that provides HTTP services in sync with the current HTTP standards.
builddeps  :
    - pkgconfig(apr-util-1)
    - pkgconfig(libnghttp2)
    - pkgconfig(libpcre)
    - pkgconfig(libxcrypt)
    - pkgconfig(openssl)
    - fcgi-devel
    - openldap-devel
    - perl
setup      : |
    %apply_patches
    cat $pkgfiles/solus.layout >> config.layout
    %configure \
        --datadir=/usr/share/httpd \
        --disable-static \
        --enable-alias \
        --enable-allowmethods \
        --enable-auth-basic \
        --enable-auth-form \
        --enable-authn-file \
        --enable-authnz-fcgi \
        --enable-authz-user \
        --enable-autoindex \
        --enable-cache \
        --enable-cache-disk \
        --enable-cgi \
        --enable-dav \
        --enable-dav-fs \
        --enable-dir \
        --enable-disk-cache \
        --enable-deflate \
        --enable-expires \
        --enable-headers \
        --enable-http2 \
        --enable-layout=Solus \
        --enable-mime \
        --enable-mpms-shared="all" \
        --enable-proxy-fcgi \
        --enable-proxy-http2 \
        --enable-remoteip \
        --enable-rewrite \
        --enable-so \
        --enable-ssl \
        --enable-static-fcgistarter \
        --enable-status \
        --enable-worker=static \
        --sysconfdir=/usr/share/defaults/httpd \
        --with-mpm=worker
build      : |
    %make
install    : |
    %make_install -j1
    # Install httpd systemd stuff
    install -Dm00644 $pkgfiles/httpd.service $installdir/%libdir%/systemd/system/httpd.service
    install -Dm00644 $pkgfiles/httpd.sysusers $installdir/%libdir%/sysusers.d/httpd.conf
    install -Dm00644 $pkgfiles/httpd.tmpfiles $installdir/%libdir%/tmpfiles.d/httpd.conf
    # Cleanup
    rm -rf $installdir/{run,var}
